# Site settings
title: Ting Chang
email: tingfchang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog for Ting Chang. Currently taking the Web Development bootcamp at Lighthouse Labs. Hoping to establish myself in this field. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com" # the base hostname & protocol for your site
twitter_username: tingfchang
github_username:  tfchang

# Build settings
markdown: kramdown
